name: defiscan
description: DeFi Scan - Mobile BlockChain Explorer for cryptocurrency accounts.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  ethers:
    git:
      url: https://github.com/bisi-dev/ethers.git
  ens_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.6
  intl: ^0.18.0
  localization: ^2.1.0
  meta: ^1.9.1
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/i18n/
