name: defiscan
description: DeFi Scan - Mobile BlockChain Explorer for cryptocurrency accounts.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  ethers:
    git:
      url: https://github.com/bisi-dev/ethers.git
  ens_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_swipe_action_cell: ^3.1.2
  google_fonts: ^4.0.4
  hive: ^2.2.3
  http: ^0.13.6
  intl: ^0.18.0
  localization: ^2.1.0
  lottie: ^2.4.0
  meta: ^1.9.1
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_lints: ^1.0.0
  hive_generator: ^2.0.0
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - lib/i18n/
