name: defiscan
description: DeFi Scan - Mobile BlockChain Explorer for cryptocurrency accounts.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  ethers:
  ens_dart: ^1.0.0
  flutter_settings_ui: ^2.0.1
  flutter_swipe_action_cell: ^2.2.0
  font_awesome_flutter: ^9.0.0
  getwidget: ^2.0.4
  google_fonts:
  http: ^0.13.4
  intl: ^0.17.0
  launch_review: ^3.0.1
  loading_animation_widget:
  provider: ^6.0.0
  shared_preferences: ^2.0.13
  sqflite:
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
